format = "$username$sudo$all"

[character]
success_symbol = "[\\$](bold green) "
error_symbol = "[\\$](bold red) "

[username]
show_always = true
format = "[$user]($style) "
style_user = "#20b35b"
style_root = "#333333"

[sudo]
style = "bold red"
format = "as [$symbol]($style) in "
symbol = "sudo"
disabled = false

[git_branch]
style = "italic red"
symbol = " "

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
format = "🐪 "

[package]
symbol = " "

[python]
symbol = " "

[spack]
symbol = "🅢 "

[rust]
symbol = " "

